apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-monitoring
  namespace: prometheus-system
spec:
  chart:
    spec:
      version: ">=13.0.0 <14.0.0"
  values:
    alertmanager:
      ingress:
        hosts:
          - alermanager.prod
    grafana:
      ingress:
        hosts:
          - grafana.prod
    prometheus:
      ingress:
        hosts:
          - prometheus.prod
