apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-monitoring
  namespace: prometheus-system
spec:
  chart:
    spec:
      version: "13.2.1"
  values:
    alertmanager:
      ingress:
        hosts:
          - alermanager.stag
    grafana:
      ingress:
        hosts:
          - grafana.stag
    prometheus:
      ingress:
        hosts:
          - prometheus.stag
